dist: focal
addons:
  snaps:
    - name: dotnet-sdk
      confinement: classic
      channel: 5.0/beta

language: minimal

script:
  - dotnet-sdk.dotnet publish --runtime win-x64
  - dotnet-sdk.dotnet publish --runtime linux-x64
  - dotnet-sdk.dotnet publish --runtime osx-x64
  - cd bin/Debug/net5.0/win-x64/publish/
  - zip -r ../../../../../win-x64-csharp-to-json-converter.zip *

  # Linux build and file upload is deactivated as executing builds created on Travis CI throw the following error:
  # -bash: ./csharp-to-json-converter: cannot execute binary file: Exec format error
  #    
  # For more updates on this, have a look at GitHub or StackOverflow:
  # - https://stackoverflow.com/questions/63477729/net-cross-platform-application-works-only-when-i-build-it-on-windows-but-not-w?noredirect=1#comment112248854_63477729
  # - https://github.com/dotnet/sdk/issues/12977
  #
  # If fixed, uncomment the following lines:
  #  - cd ../../linux-x64/publish/
  #  - zip -r ../../../../../linux-x64-csharp-to-json-converter.zip *
  - cd ../../osx-x64/publish/
  - zip -r ../../../../../osx-x64-csharp-to-json-converter.zip *
  - cd ../../../../..

deploy:
  draft: true
  provider: releases
  api_key:
    secure: M30bXS0TxcjHP3QkJLu6amA71sFhYriTiVYLJrxiyjA9DUpkjDNAjQWF5GxMRxHuzyDywVCbYsmYjWbCIh+RJWgGHbDAGQFgetwSJx2eKogizBY+WGD38wb4jnvwROZ7BdCyHuDMXYlVSFoEA2PoPwRRQuYPzutJelb0fPvnIigi2k4ZfLkr3TrlREQSNNN03l71+YHdBKIy3v16JuLwFHdp3P+qxSepDRSEEI/OqMWtaTJF1KvorDgdq8kDOVyXsBtRGdjkfbMQfYC346xyoOFrnoCdM/SsqOo3ufirH68kBGRUtpTJuDtLS78WYdffG3o6ONe+GYSZRvKJ+4gruOfDs5npjHf/mG4zGsNXBvIEsaTE+IfLSDsd5rgyq5m63K3MEQHn3xMhzfOAwpZnRQhwQVnWeDJkUUKL3s+tWoV8HopvqNsAYyREc0se7C93JBs5Zj1eIdE4NVAtqnFLUpBVtz5HHnZCtHVOG6hdoUAi/R8Z0rL6JePRs+nla2BOy4+jHGJspMoyntgHEe/N87MXuxhXwLkmg1TnbU2+7NKRDsK9FBBgJqp5TRfn3gN7GzvlLlZs8jtIgbtI3F6PhMeaAembrLqnCKUvtvcaA2aA7xTHPoci8aBBskMM5z4Btt4uWZar1ficP2KdrNT5ncnrM4YxV5AXyReQeBdghbI=
  file:
    - win-x64-csharp-to-json-converter.zip
    - osx-x64-csharp-to-json-converter.zip
  # See comment in script section for more information:
  #    - linux-x64-csharp-to-json-converter.zip

  on:
    repo: softvis-research/csharp-to-json-converter
  skip_cleanup: true
